<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Version>0.1</Version>
        <Authors>TheVSAKeeper</Authors>
        <Company>TheVSAKeeper</Company>
        <Description>
            Description
        </Description>
        <Copyright>Copyright 2022-2024 TheVSAKeeper</Copyright>
        <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Blazorise.Components" Version="1.5.2"/>
        <PackageReference Include="Blazorise.FluentValidation" Version="1.5.2"/>
        <PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.5.2"/>
        <PackageReference Include="Blazorise.LoadingIndicator" Version="1.5.2"/>
        <PackageReference Include="Calabonga.PagedListCore" Version="1.0.4"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.1"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.5"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.5" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.5"/>
        <PackageReference Include="Calabonga.Microservices.Core" Version="5.1.0"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3"/>
        <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Blazorise" Version="1.5.2"/>
        <PackageReference Include="Blazorise.Material" Version="1.5.2"/>
        <PackageReference Include="Blazorise.Icons.Material" Version="1.5.2"/>
        <PackageReference Include="Blazorise.DataGrid" Version="1.5.2"/>
    </ItemGroup>

    <ItemGroup>
        <ServiceWorker Include="wwwroot\service-worker.js">
            <PublishedContent>wwwroot\service-worker.published.js</PublishedContent>
        </ServiceWorker>
    </ItemGroup>

    <ItemGroup>
        <_ContentIncludedByDefault Remove="Components\TodoApp\TodoItem.razor"/>
        <_ContentIncludedByDefault Remove="Components\TodoApp\TodoItems.razor"/>
        <_ContentIncludedByDefault Remove="Layouts\MainLayout.razor"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Endpoints\BaseEndpoints\Components\"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="Endpoints\BaseEndpoints\Components\Layout\FooterMenu.razor"/>
        <AdditionalFiles Include="Endpoints\BaseEndpoints\Components\Layout\SideMenu.razor"/>
        <AdditionalFiles Include="Endpoints\BaseEndpoints\Components\Layout\ThemeColorSelector.razor"/>
        <AdditionalFiles Include="Endpoints\BaseEndpoints\Components\Layout\TopMenu.razor"/>
        <AdditionalFiles Include="Endpoints\BaseEndpoints\Layouts\MainLayout.razor"/>
    </ItemGroup>

</Project>
