<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Version>0.1</Version>
        <Authors>TheVSAKeeper</Authors>
        <Company>TheVSAKeeper</Company>
        <Description>
            Description
        </Description>
        <Copyright>Copyright 2022-2024 TheVSAKeeper</Copyright>
        <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Blazorise.Components" Version="1.5.2"/>
        <PackageReference Include="Blazorise.FluentValidation" Version="1.5.2"/>
        <PackageReference Include="Blazorise.Icons.FontAwesome" Version="1.5.2"/>
        <PackageReference Include="Blazorise.LoadingIndicator" Version="1.5.2"/>
        <PackageReference Include="Calabonga.PagedListCore" Version="1.0.4"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.1"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.5"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.5" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.5"/>
        <PackageReference Include="Calabonga.Microservices.Core" Version="5.1.0"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3"/>
        <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Blazorise" Version="1.5.2"/>
        <PackageReference Include="Blazorise.Material" Version="1.5.2"/>
        <PackageReference Include="Blazorise.Icons.Material" Version="1.5.2"/>
        <PackageReference Include="Blazorise.DataGrid" Version="1.5.2"/>
    </ItemGroup>

    <ItemGroup>
        <ServiceWorker Include="wwwroot\service-worker.js">
            <PublishedContent>wwwroot\service-worker.published.js</PublishedContent>
        </ServiceWorker>
    </ItemGroup>

    <ItemGroup>
        <_ContentIncludedByDefault Remove="Components\TodoApp\TodoItem.razor"/>
        <_ContentIncludedByDefault Remove="Components\TodoApp\TodoItems.razor"/>
        <_ContentIncludedByDefault Remove="Layouts\MainLayout.razor"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Endpoints\BaseEndpoints\Components\"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="Endpoints\BaseEndpoints\Components\Layout\FooterMenu.razor"/>
        <AdditionalFiles Include="Endpoints\BaseEndpoints\Components\Layout\SideMenu.razor"/>
        <AdditionalFiles Include="Endpoints\BaseEndpoints\Components\Layout\ThemeColorSelector.razor"/>
        <AdditionalFiles Include="Endpoints\BaseEndpoints\Components\Layout\TopMenu.razor"/>
        <AdditionalFiles Include="Endpoints\BaseEndpoints\Layouts\MainLayout.razor"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\..\Surveys.Domain\Gender.cs">
            <Link>Endpoints\PatientEndpoints\ViewModels\Gender.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Domain\QuestionType.cs">
            <Link>Endpoints\QuestionEndpoints\ViewModels\QuestionType.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Domain\SurveyStatus.cs">
            <Link>Endpoints\SurveyEndpoints\ViewModels\SurveyStatus.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\AnamnesisMessages\ViewModels\AnamnesisCreateViewModel.cs">
            <Link>Endpoints\AnamnesisEndpoints\ViewModels\AnamnesisCreateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\AnamnesisMessages\ViewModels\AnamnesisUpdateViewModel.cs">
            <Link>Endpoints\AnamnesisEndpoints\ViewModels\AnamnesisUpdateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\AnamnesisMessages\ViewModels\AnamnesisViewModel.cs">
            <Link>Endpoints\AnamnesisEndpoints\ViewModels\AnamnesisViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\AnamnesisTemplateMessages\ViewModels\AnamnesisTemplateCreateViewModel.cs">
            <Link>Endpoints\AnamnesisTemplateEndpoints\ViewModels\AnamnesisTemplateCreateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\AnamnesisTemplateMessages\ViewModels\AnamnesisTemplateUpdateViewModel.cs">
            <Link>Endpoints\AnamnesisTemplateEndpoints\ViewModels\AnamnesisTemplateUpdateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\AnamnesisTemplateMessages\ViewModels\AnamnesisTemplateViewModel.cs">
            <Link>Endpoints\AnamnesisTemplateEndpoints\ViewModels\AnamnesisTemplateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\PatientMessages\ViewModels\PatientsCreateViewModel.cs">
            <Link>Endpoints\PatientEndpoints\ViewModels\PatientsCreateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\PatientMessages\ViewModels\PatientsViewModel.cs">
            <Link>Endpoints\PatientEndpoints\ViewModels\PatientsViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\QuestionMessages\ViewModels\QuestionCreateViewModel.cs">
            <Link>Endpoints\QuestionEndpoints\ViewModels\QuestionCreateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\QuestionMessages\ViewModels\QuestionUpdateViewModel.cs">
            <Link>Endpoints\QuestionEndpoints\ViewModels\QuestionUpdateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\QuestionMessages\ViewModels\QuestionViewModel.cs">
            <Link>Endpoints\QuestionEndpoints\ViewModels\QuestionViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\QuestionOptionMessages\ViewModels\QuestionOptionCreateViewModel.cs">
            <Link>Endpoints\QuestionEndpoints\ViewModels\QuestionOptionCreateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\QuestionOptionMessages\ViewModels\QuestionOptionUpdateViewModel.cs">
            <Link>Endpoints\QuestionEndpoints\ViewModels\QuestionOptionUpdateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\QuestionOptionMessages\ViewModels\QuestionOptionViewModel.cs">
            <Link>Endpoints\QuestionEndpoints\ViewModels\QuestionOptionViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\ResponseAnswerMessages\ViewModels\ResponseAnswerCreateViewModel.cs">
            <Link>Endpoints\ResponseEndpoints\ViewModels\ResponseAnswerCreateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\ResponseAnswerMessages\ViewModels\ResponseAnswerUpdateViewModel.cs">
            <Link>Endpoints\ResponseEndpoints\ViewModels\ResponseAnswerUpdateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\ResponseAnswerMessages\ViewModels\ResponseAnswerViewModel.cs">
            <Link>Endpoints\ResponseEndpoints\ViewModels\ResponseAnswerViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\ResponseMessages\ViewModels\ResponseCreateViewModel.cs">
            <Link>Endpoints\ResponseEndpoints\ViewModels\ResponseCreateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\ResponseMessages\ViewModels\ResponseUpdateViewModel.cs">
            <Link>Endpoints\ResponseEndpoints\ViewModels\ResponseUpdateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\ResponseMessages\ViewModels\ResponseViewModel.cs">
            <Link>Endpoints\ResponseEndpoints\ViewModels\ResponseViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\SurveyMessages\ViewModels\SurveyCreateViewModel.cs">
            <Link>Endpoints\SurveyEndpoints\ViewModels\SurveyCreateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\SurveyMessages\ViewModels\SurveyUpdateViewModel.cs">
            <Link>Endpoints\SurveyEndpoints\ViewModels\SurveyUpdateViewModel.cs</Link>
        </Compile>
        <Compile Include="..\..\Surveys.Web\Application\Messaging\SurveyMessages\ViewModels\SurveyViewModel.cs">
            <Link>Endpoints\SurveyEndpoints\ViewModels\SurveyViewModel.cs</Link>
        </Compile>
    </ItemGroup>

</Project>
